name: Publish new files
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mathieudutour/github-tag-action@v5.6
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: yarn run build
      - run: node tmp/main.js
      - uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: |
            out/en.json
            out/compendium/*.json
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body_path: "tmp/changes.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
